# Generated by Django 5.1.4 on 2025-09-12 05:12

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_management', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField()),
                ('question_text_uz', ckeditor.fields.RichTextField(null=True)),
                ('question_text_ru', ckeditor.fields.RichTextField(null=True)),
                ('question_type', models.CharField(choices=[('text', 'Matnli javob'), ('choice', 'Variant tanlash'), ('image_choice', 'Rasmli variant'), ('composite', 'Bir nechta inputli savol')], max_length=20)),
                ('level', models.PositiveIntegerField()),
                ('correct_text_answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('correct_text_answer_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('correct_text_answer_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video_file_uz', models.FileField(blank=True, null=True, upload_to='Video_darsliklar/')),
                ('video_file_ru', models.FileField(blank=True, null=True, upload_to='Video_darsliklar/')),
                ('video_url_uz', models.URLField(blank=True, null=True)),
                ('video_url_ru', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Bob nomi')),
                ('name_uz', models.CharField(max_length=500, null=True, verbose_name='Bob nomi')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='Bob nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='app_user.subject', verbose_name='Tegishli fan')),
            ],
            options={
                'verbose_name': 'Fan Bobi',
                'verbose_name_plural': 'Fan Boblari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='app_user.student', verbose_name="O'quvchilar")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app_user.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='CompositeSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(blank=True, null=True)),
                ('text1_uz', models.TextField(blank=True, null=True)),
                ('text1_ru', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text2_uz', models.TextField(blank=True, null=True)),
                ('text2_ru', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='app_teacher.question')),
            ],
            options={
                'verbose_name': 'Kichik savol',
                'verbose_name_plural': 'Kichik savollar',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices/images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app_teacher.question')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
        migrations.CreateModel(
            name='TeacherProductExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_coin', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.product')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exchanges', to='app_user.teacher')),
            ],
            options={
                'verbose_name': 'O‘qituvchining mahsulot almashtiruvi',
                'verbose_name_plural': 'O‘qituvchilarning mahsulot almashtiruvi',
            },
        ),
        migrations.CreateModel(
            name='TeacherRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('score', 'Ball qo‘shildi'), ('coin', 'Tanga qo‘shildi'), ('subscription_day', 'Obuna kuni qo‘shildi')], max_length=20, verbose_name='Rag‘bat turi')),
                ('amount', models.PositiveIntegerField(verbose_name='Qiymati (ball, tanga yoki kun)')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Sababi (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rewards', to='app_user.student', verbose_name='O‘quvchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_rewards', to='app_user.teacher', verbose_name='O‘qituvchi')),
            ],
            options={
                'verbose_name': 'Rag‘bat yozuvi',
                'verbose_name_plural': 'Rag‘bat yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('coin', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_user.teacher')),
            ],
            options={
                'verbose_name': 'O‘qituvchi bali',
                'verbose_name_plural': 'O‘qituvchilar ballari',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Mavzu nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Mavzu nomi')),
                ('video_url_uz', models.URLField(blank=True, null=True, verbose_name='Mavzu videosi')),
                ('video_url_ru', models.URLField(blank=True, null=True, verbose_name='Mavzu videosi')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mavzu matni')),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mavzu matni')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mavzu matni')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Qulflangan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='app_teacher.chapter', verbose_name='Tegishli bob')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_teacher.topic'),
        ),
        migrations.CreateModel(
            name='UnsolvedQuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('pending', 'Ko‘rib chiqilmoqda'), ('answered', 'Javob yozildi')], default='pending', max_length=20)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='O‘qituvchi javobi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_reports', to='app_user.teacher')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsolved_reports', to='app_teacher.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsolved_reports', to='app_user.student')),
                ('teachers', models.ManyToManyField(related_name='unsolved_reports', to='app_user.teacher')),
            ],
            options={
                'verbose_name': 'Ishlanmagan savol',
                'verbose_name_plural': 'Ishlanmagan savollar',
            },
        ),
    ]
