# Generated by Django 5.1.4 on 2025-10-25 08:24

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionOpenAi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', ckeditor.fields.RichTextField(verbose_name='AI generatsiya qilgan savol')),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('data_seed', models.JSONField(blank=True, null=True, verbose_name='Raqamli parametrlar (AI tomonidan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('base_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_versions', to='app_teacher.question', verbose_name='Asosiy savol')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='app_teacher.topic', verbose_name='Tegishli mavzu')),
            ],
            options={
                'verbose_name': 'Generatsiya qilingan savol',
                'verbose_name_plural': 'Generatsiya qilingan savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedChoiceOpenAi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('generated_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_choices', to='app_teacher.generatedquestionopenai')),
            ],
            options={
                'verbose_name': 'AI variant',
                'verbose_name_plural': 'AI variantlar',
            },
        ),
        migrations.CreateModel(
            name='GeneratedSubQuestionOpenAi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('text2', models.TextField(blank=True, null=True)),
                ('generated_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_sub_questions', to='app_teacher.generatedquestionopenai')),
            ],
            options={
                'verbose_name': 'AI kichik savol',
                'verbose_name_plural': 'AI kichik savollar',
            },
        ),
    ]
