# Generated by Django 5.1.4 on 2025-10-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0002_generatedquestionopenai_generatedchoiceopenai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestionopenai',
            name='base_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_versions', to='app_teacher.question', verbose_name='Asosiy savol'),
        ),
    ]
