# Generated by Django 5.1.4 on 2025-10-25 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0003_alter_generatedquestionopenai_base_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedquestionopenai',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI generatsiya qilingan savol', 'verbose_name_plural': 'AI generatsiya qilingan savollar'},
        ),
        migrations.RenameField(
            model_name='generatedchoiceopenai',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='generatedquestionopenai',
            old_name='correct_answer',
            new_name='correct_answer_ru',
        ),
        migrations.RenameField(
            model_name='generatedsubquestionopenai',
            old_name='text1',
            new_name='text1_ru',
        ),
        migrations.RenameField(
            model_name='generatedsubquestionopenai',
            old_name='text2',
            new_name='text1_uz',
        ),
        migrations.RemoveField(
            model_name='generatedquestionopenai',
            name='base_question',
        ),
        migrations.RemoveField(
            model_name='generatedquestionopenai',
            name='generated_text',
        ),
        migrations.RemoveField(
            model_name='generatedsubquestionopenai',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='generatedchoiceopenai',
            name='text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedquestionopenai',
            name='correct_answer_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generatedquestionopenai',
            name='generated_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='AI generatsiya qilgan savol (RU)'),
        ),
        migrations.AddField(
            model_name='generatedquestionopenai',
            name='generated_text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='AI generatsiya qilgan savol (UZ)'),
        ),
        migrations.AddField(
            model_name='generatedquestionopenai',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('composite', 'Composite')], default='text', max_length=20, verbose_name='Savol turi'),
        ),
        migrations.AddField(
            model_name='generatedsubquestionopenai',
            name='correct_answer_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generatedsubquestionopenai',
            name='correct_answer_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generatedsubquestionopenai',
            name='text2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedsubquestionopenai',
            name='text2_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
