# Generated by Django 5.1.4 on 2025-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0004_alter_generatedquestionopenai_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsolvedquestionreport',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
