# Generated by Django 5.1.4 on 2025-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0005_unsolvedquestionreport_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
