# Generated by Django 5.1.4 on 2025-11-27 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0020_delete_systemcoupon'),
        ('app_teacher', '0006_remove_choice_image_choice_image_url'),
        ('app_user', '0008_alter_student_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCouponTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Kupon ishlatilgan sana')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_transactions', to='app_management.coupon_tutor_student', verbose_name='Kupon kodi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_used_coupons', to='app_user.student', verbose_name='Kuponni ishlatgan student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_coupon_transactions', to='app_user.teacher', verbose_name='Kupon egasi (Teacher)')),
            ],
        ),
    ]
