# Generated by Django 5.1.4 on 2025-11-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0007_teachercoupontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercoupontransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'lov summasi"),
            preserve_default=False,
        ),
    ]
