# Generated by Django 5.1.4 on 2026-05-27 22:43

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0008_teachercoupontransaction_payment_amount'),
        ('app_user', '0021_alter_parentstudentrelation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherproductexchange',
            options={'verbose_name': "O'qituvchining mahsulot almashtiruvi", 'verbose_name_plural': "O'qituvchilarning mahsulot almashtiruvi"},
        ),
        migrations.AlterModelOptions(
            name='teacherrewardlog',
            options={'ordering': ['-created_at'], 'verbose_name': "Rag'bat yozuvi", 'verbose_name_plural': "Rag'bat yozuvlari"},
        ),
        migrations.AlterModelOptions(
            name='teacherscore',
            options={'ordering': ['-score'], 'verbose_name': "O'qituvchi bali", 'verbose_name_plural': "O'qituvchilar ballari"},
        ),
        migrations.AlterField(
            model_name='teacherrewardlog',
            name='reward_type',
            field=models.CharField(choices=[('score', "Ball qo'shildi"), ('coin', "Tanga qo'shildi"), ('subscription_day', "Obuna kuni qo'shildi")], max_length=20, verbose_name="Rag'bat turi"),
        ),
        migrations.AlterField(
            model_name='teacherrewardlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rewards', to='app_user.student', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='teacherrewardlog',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_rewards', to='app_user.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='unsolvedquestionreport',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="O'qituvchi javobi"),
        ),
        migrations.AlterField(
            model_name='unsolvedquestionreport',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('answered', 'Javob yozildi')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherFineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(choices=[('score', 'Ball'), ('coin', 'Tanga')], max_length=10, verbose_name='Jarima turi')),
                ('amount', models.PositiveIntegerField(verbose_name='Miqdori')),
                ('reason', models.TextField(verbose_name='Sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_fines', to=settings.AUTH_USER_MODEL, verbose_name="Jarima qo'ygan")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_fines', to='app_user.student', verbose_name="Jarima olgan o'quvchi")),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': 'Jarimalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
