# Generated by Django 5.1.4 on 2025-09-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bob bo‘yicha yutuq',
                'verbose_name_plural': 'Boblar bo‘yicha yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='Diagnost_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('result', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_coin', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulotga almashtirish',
                'verbose_name_plural': 'Mahsulotga almashtirishlar',
            },
        ),
        migrations.CreateModel(
            name='StudentReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student referali',
                'verbose_name_plural': 'Student referallari',
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('coin', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Talaba bali',
                'verbose_name_plural': 'Talabalar ballari',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='StudentScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_coin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ball olish tarixi',
                'verbose_name_plural': 'Ballar olish tarixi',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicHelpRequestIndependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('question_json', models.JSONField()),
                ('result_json', models.JSONField()),
                ('commit', models.TextField(blank=True, null=True, verbose_name='O‘qituvchi izohi')),
                ('commit_uz', models.TextField(blank=True, null=True, verbose_name='O‘qituvchi izohi')),
                ('commit_ru', models.TextField(blank=True, null=True, verbose_name='O‘qituvchi izohi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Yuborilgan'), ('reviewing', 'Muhokamada'), ('answered', 'Javob berildi')], default='sent', max_length=20, verbose_name='Savol holati')),
            ],
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mavzu bo‘yicha yutuq',
                'verbose_name_plural': 'Mavzular bo‘yicha yutuqlar',
                'ordering': ['-completed_at'],
            },
        ),
    ]
