# Generated by Django 5.1.4 on 2025-09-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_management', '0001_initial'),
        ('app_student', '0001_initial'),
        ('app_teacher', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='app_teacher.chapter'),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='app_user.student'),
        ),
        migrations.AddField(
            model_name='diagnost_student',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='app_teacher.chapter'),
        ),
        migrations.AddField(
            model_name='diagnost_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.student'),
        ),
        migrations.AddField(
            model_name='diagnost_student',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.subject'),
        ),
        migrations.AddField(
            model_name='diagnost_student',
            name='topic',
            field=models.ManyToManyField(blank=True, to='app_teacher.topic'),
        ),
        migrations.AddField(
            model_name='productexchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.product'),
        ),
        migrations.AddField(
            model_name='productexchange',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exchanges', to='app_user.student'),
        ),
        migrations.AddField(
            model_name='studentreferral',
            name='referred',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='app_user.student'),
        ),
        migrations.AddField(
            model_name='studentreferral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_students', to='app_user.student'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.student'),
        ),
        migrations.AddField(
            model_name='studentscorelog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_teacher.question'),
        ),
        migrations.AddField(
            model_name='studentscorelog',
            name='student_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_student.studentscore'),
        ),
        migrations.AddField(
            model_name='topichelprequestindependent',
            name='chapters',
            field=models.ManyToManyField(to='app_teacher.chapter'),
        ),
        migrations.AddField(
            model_name='topichelprequestindependent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='app_user.student'),
        ),
        migrations.AddField(
            model_name='topichelprequestindependent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.subject'),
        ),
        migrations.AddField(
            model_name='topichelprequestindependent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_user.teacher', verbose_name='Tekshiruvchi o‘qituvchi'),
        ),
        migrations.AddField(
            model_name='topichelprequestindependent',
            name='topics',
            field=models.ManyToManyField(to='app_teacher.topic'),
        ),
        migrations.AddField(
            model_name='helprequestmessagelog',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='app_student.topichelprequestindependent'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='app_teacher.topic'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='app_user.student'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterprogress',
            unique_together={('user', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='studentscore',
            unique_together={('student',)},
        ),
        migrations.AlterUniqueTogether(
            name='studentscorelog',
            unique_together={('student_score', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='helprequestmessagelog',
            unique_together={('help_request', 'chat_id')},
        ),
    ]
