# Generated by Django 5.1.4 on 2025-09-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0003_studentcoupontransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcoupontransaction',
            old_name='student_cashback_amount',
            new_name='cashback_amount',
        ),
        migrations.RemoveField(
            model_name='studentcoupontransaction',
            name='teacher_cashback_amount',
        ),
    ]
