# Generated by Django 5.1.4 on 2025-09-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0008_referral_tutor_student'),
        ('app_student', '0004_rename_student_cashback_amount_studentcoupontransaction_cashback_amount_and_more'),
        ('app_user', '0002_alter_teacher_options_alter_tutor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='To‘lov summasi')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Studentga berilgan bonus')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Referal ishlatilgan sana')),
                ('by_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions_student', to='app_user.student', verbose_name='Referal link egasi (student)')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transactions', to='app_management.referral_tutor_student', verbose_name='Referal kodi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_student_referrals', to='app_user.student', verbose_name='Referal link orqali kelgan student')),
            ],
            options={
                'verbose_name': 'Student referal tranzaksiyasi',
                'verbose_name_plural': 'Student referal tranzaksiyalari',
            },
        ),
    ]
