# Generated by Django 5.1.4 on 2025-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0005_studentreferraltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreferraltransaction',
            name='referral',
        ),
    ]
