# Generated by Django 5.1.4 on 2025-10-22 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0006_remove_studentreferraltransaction_referral'),
        ('app_user', '0006_alter_parent_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('SCORE_TO_COIN', 'Ball → Tanga'), ('COIN_TO_SOM', 'Tanga → Soʻm')], max_length=20)),
                ('amount_from', models.PositiveIntegerField()),
                ('amount_to', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.student')),
            ],
        ),
    ]
