# Generated by Django 5.1.4 on 2025-10-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0007_conversionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='topichelprequestindependent',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Ko‘rildi'),
        ),
    ]
