# Generated by Django 5.1.4 on 2025-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0008_topichelprequestindependent_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='status',
            field=models.CharField(choices=[('sent', 'Yuborilgan'), ('seen', 'Ko‘rildi'), ('reviewing', 'Ko‘rib chiqilmoqda'), ('answered', 'Javob berildi'), ('closed', 'Yopildi / Yakunlandi'), ('rejected', 'Rad etildi')], default='sent', max_length=20, verbose_name='Savol holati'),
        ),
    ]
