# Generated by Django 5.1.4 on 2025-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0009_alter_topichelprequestindependent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Konvertatsiya tarixi', 'verbose_name_plural': 'Konvertatsiyalar tarixi'},
        ),
        migrations.AddField(
            model_name='conversionhistory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='conversionhistory',
            name='som_after',
            field=models.PositiveIntegerField(default=0, verbose_name='So‘m balans (konvertatsiyadan keyin)'),
        ),
        migrations.AddField(
            model_name='conversionhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='som',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='conversion_type',
            field=models.CharField(choices=[('SCORE_TO_COIN', 'Ball → Tanga'), ('SCORE_TO_SOM', 'Ball → Soʻm'), ('COIN_TO_SOM', 'Tanga → Soʻm')], max_length=20),
        ),
    ]
