# Generated by Django 5.1.4 on 2025-11-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0010_alter_conversionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnost_student',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
