# Generated by Django 5.1.4 on 2025-11-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0011_diagnost_student_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productexchange',
            name='status',
        ),
        migrations.AddField(
            model_name='productexchange',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productexchange',
            name='delivery_status',
            field=models.CharField(choices=[('new', 'Yangi kelgan xabar'), ('processing', 'Jarayonda'), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi'), ('confirmed', 'O‘quvchi tasdiqladi')], default='new', max_length=20, verbose_name='Tovar holati'),
        ),
        migrations.AddField(
            model_name='productexchange',
            name='is_confirmed_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
