# Generated by Django 5.1.4 on 2025-11-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0012_remove_productexchange_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productexchange',
            name='delivery_status',
            field=models.CharField(choices=[('new', 'Yangi kelgan xabar'), ('viewed', 'Ko‘rildi'), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi'), ('confirmed', 'O‘quvchi tasdiqladi')], default='new', max_length=20, verbose_name='Tovar holati'),
        ),
    ]
