# Generated by Django 5.1.4 on 2026-03-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0013_alter_productexchange_delivery_status'),
        ('app_user', '0014_user_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailyCoinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('coin_count', models.PositiveIntegerField(default=0, verbose_name="Yig'ilgan tanga soni")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_coin_logs', to='app_user.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Kunlik tanga tarixi',
                'verbose_name_plural': 'Kunlik tanga tarixi',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
