# Generated by Django 5.1.4 on 2026-03-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0014_studentdailycoinlog'),
        ('app_user', '0015_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name="O'tkazilgan so'm")),
                ('otp_code', models.CharField(max_length=5, verbose_name='OTP kod')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlandi')),
                ('is_expired', models.BooleanField(default=False, verbose_name="Muddati o'tgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="So'rov vaqti")),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiq vaqti')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='app_user.student', verbose_name='Qabul qiluvchi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='app_user.student', verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': "So'm o'tkazish",
                'verbose_name_plural': "So'm o'tkazishlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
