# Generated by Django 5.1.4 on 2026-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0015_somtransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscorelog',
            name='award_type',
            field=models.CharField(choices=[('coin', 'Tanga'), ('score', 'Ball')], default='score', max_length=5, verbose_name='Mukofot turi'),
        ),
    ]
