# Generated by Django 5.1.4 on 2026-05-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0016_studentscorelog_award_type'),
        ('app_user', '0021_alter_parentstudentrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterprogress',
            options={'verbose_name': "Bob bo'yicha yutuq", 'verbose_name_plural': "Boblar bo'yicha yutuqlar"},
        ),
        migrations.AlterModelOptions(
            name='topicprogress',
            options={'ordering': ['-completed_at'], 'verbose_name': "Mavzu bo'yicha yutuq", 'verbose_name_plural': "Mavzular bo'yicha yutuqlar"},
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='som_after',
            field=models.PositiveIntegerField(default=0, verbose_name="So'm balans (konvertatsiyadan keyin)"),
        ),
        migrations.AlterField(
            model_name='productexchange',
            name='delivery_status',
            field=models.CharField(choices=[('new', 'Yangi kelgan xabar'), ('viewed', "Ko'rildi"), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi'), ('confirmed', "O'quvchi tasdiqladi")], default='new', max_length=20, verbose_name='Tovar holati'),
        ),
        migrations.AlterField(
            model_name='studentcoupontransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='studentreferraltransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='commit',
            field=models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi"),
        ),
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='commit_ru',
            field=models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi"),
        ),
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='commit_uz',
            field=models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi"),
        ),
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name="Ko'rildi"),
        ),
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='status',
            field=models.CharField(choices=[('sent', 'Yuborilgan'), ('seen', "Ko'rildi"), ('reviewing', "Ko'rib chiqilmoqda"), ('answered', 'Javob berildi'), ('closed', 'Yopildi / Yakunlandi'), ('rejected', 'Rad etildi')], default='sent', max_length=20, verbose_name='Savol holati'),
        ),
        migrations.AlterField(
            model_name='topichelprequestindependent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_user.teacher', verbose_name="Tekshiruvchi o'qituvchi"),
        ),
    ]
