# Generated by Django 5.1.4 on 2025-09-12 05:11

import django.db.models.deletion
import django.utils.timezone
import django_app.app_user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Sinf nomi')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='Subject_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Fan bo'limi")),
            ],
            options={
                'verbose_name': "Fan Bo'limi",
                'verbose_name_plural': "Fan Bo'limi",
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('parent', 'Parent'), ('tutor', 'Tutor')], default='student', max_length=10, verbose_name='Foydalanuvchi roli')),
                ('sms_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='SMS kod')),
                ('telegram_id', models.BigIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='To‘liq ism')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('districts', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ro‘yxatdan o‘tgan sana')),
                ('status', models.BooleanField(default=False, verbose_name='Holat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(default=django_app.app_user.models.generate_daily_user_id, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='To‘liq ism')),
                ('region', models.CharField(max_length=200, verbose_name='Viloyat')),
                ('districts', models.CharField(max_length=200, verbose_name='Tuman')),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('brithday', models.CharField(max_length=20, verbose_name='Tug‘ilgan kun')),
                ('academy_or_school', models.CharField(max_length=200, verbose_name='Akademiya yoki maktab')),
                ('academy_or_school_name', models.CharField(max_length=500, verbose_name='Muassasa nomi')),
                ('document_type', models.CharField(max_length=50, verbose_name='Hujjat turi')),
                ('document', models.CharField(max_length=20, verbose_name='Hujjat raqami')),
                ('type_of_education', models.CharField(max_length=200, verbose_name='Ta’lim turi')),
                ('status', models.BooleanField(default=False, verbose_name='Holat')),
                ('student_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ro‘yxatdan o‘tgan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'O‘quvchi',
                'verbose_name_plural': 'O‘quvchilar',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to='app_user.student', verbose_name='Taklif qilingan')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='app_user.student', verbose_name='Taklif qilgan')),
            ],
            options={
                'verbose_name': 'Referal',
                'verbose_name_plural': 'Referallar',
            },
        ),
        migrations.CreateModel(
            name='StudentLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='app_user.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Fan nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Fan nomi')),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to='FILES/SubjectUZ')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='FILES/SubjectRU')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('active', models.BooleanField(default=True, verbose_name='Faol fanmi?')),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='app_user.class', verbose_name='Sinf')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='app_user.subject_category', verbose_name="Fan bo'limi")),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='To‘liq ism')),
                ('region', models.CharField(max_length=200, verbose_name='Viloyat')),
                ('districts', models.CharField(max_length=200, verbose_name='Tuman')),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('brithday', models.CharField(max_length=20, verbose_name='Tug‘ilgan kun')),
                ('document_type', models.CharField(max_length=50, verbose_name='Hujjat turi')),
                ('document', models.CharField(max_length=20, verbose_name='Hujjat raqami')),
                ('status', models.BooleanField(default=False, verbose_name='Holat')),
                ('is_verified_teacher', models.BooleanField(default=False, verbose_name='O‘qituvchi')),
                ('teacher_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ro‘yxatdan o‘tgan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'O‘qituvchi',
                'verbose_name_plural': 'O‘qituvchilar',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='app_user.teacher', verbose_name='O‘qituvchilar'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='To‘liq ism')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('districts', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('tutor_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ro‘yxatdan o‘tgan sana')),
                ('status', models.BooleanField(default=False, verbose_name='Holat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'qtuvchi",
                'verbose_name_plural': "O'qtuvchi",
            },
        ),
        migrations.CreateModel(
            name='UserSMSAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlanganmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='app_user.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='app_user.student')),
            ],
            options={
                'verbose_name': 'Ota-ona va farzand bog‘lanishi',
                'verbose_name_plural': 'Ota-ona va farzand bog‘lanishlari',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('access_start', models.DateTimeField(blank=True, null=True)),
                ('access_end', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_access', to='app_user.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.subject')),
            ],
            options={
                'verbose_name': 'Fan kirish huquqi',
                'verbose_name_plural': 'Fan kirish huquqlari',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
