# Generated by Django 5.1.4 on 2025-09-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentor'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': "O'qtuvchi", 'verbose_name_plural': "O'qtuvchilar"},
        ),
    ]
