# Generated by Django 5.1.4 on 2025-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_teacher_options_alter_tutor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'O‘qituvchi', 'verbose_name_plural': 'O‘qituvchilar'},
        ),
        migrations.AddField(
            model_name='tutor',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
