# Generated by Django 5.1.4 on 2025-10-09 18:21

import django_app.app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_tutor_options_tutor_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='identification',
            field=models.CharField(default=django_app.app_user.models.generate_tutor_identification, max_length=20, unique=True),
        ),
    ]
