# Generated by Django 5.1.4 on 2025-10-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_tutor_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
