# Generated by Django 5.1.4 on 2025-10-10 04:55

import django_app.app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_parent_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='identification',
            field=models.CharField(default=django_app.app_user.models.generate_parent_identification, max_length=20, unique=True),
        ),
    ]
