# Generated by Django 5.1.4 on 2025-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_alter_parent_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Til'),
        ),
    ]
