# Generated by Django 5.1.4 on 2025-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_student_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lang',
            field=models.CharField(blank=True, default='uz', max_length=10, null=True, verbose_name='Til'),
        ),
    ]
