# Generated by Django 5.1.4 on 2025-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_alter_student_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name="Fan bo'limi"),
        ),
        migrations.AddField(
            model_name='subject_category',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name="Fan bo'limi"),
        ),
    ]
