# Generated by Django 5.1.4 on 2025-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_subject_category_name_ru_subject_category_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin'), ('parent', 'Parent'), ('tutor', 'Tutor')], default='student', max_length=10, verbose_name='Foydalanuvchi roli'),
        ),
    ]
