# Generated by Django 5.1.4 on 2026-01-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_teacherloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='support',
            field=models.BooleanField(default=False),
        ),
    ]
