# Generated by Django 5.1.4 on 2026-03-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_device_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='web/mobile'),
        ),
    ]
