# Generated by Django 5.1.4 on 2026-03-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_user_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Mentor'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin'), ('parent', 'Ota-ona'), ('tutor', "O'qtuvchi")], default='student', max_length=10, verbose_name='Foydalanuvchi roli'),
        ),
    ]
