# Generated by Django 5.1.4 on 2026-04-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'O’qituvchi', 'verbose_name_plural': 'O’qituvchilar'},
        ),
        migrations.AddField(
            model_name='parent',
            name='lang',
            field=models.CharField(blank=True, default='uz', max_length=10, null=True, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lang',
            field=models.CharField(blank=True, default='uz', max_length=10, null=True, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='lang',
            field=models.CharField(blank=True, default='uz', max_length=10, null=True, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ro’yxatdan o’tgan sana'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_verified_teacher',
            field=models.BooleanField(default=False, verbose_name='O’qituvchi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ro’yxatdan o’tgan sana'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ro’yxatdan o’tgan sana'),
        ),
    ]
