# Generated by Django 5.1.4 on 2026-04-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_alter_tutor_options_parent_lang_teacher_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='app_user.parent')),
            ],
            options={
                'verbose_name': 'Ota-ona login tarixi',
                'verbose_name_plural': 'Ota-ona login tarixi',
            },
        ),
        migrations.CreateModel(
            name='TutorLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='app_user.tutor')),
            ],
            options={
                'verbose_name': 'Tutor login tarixi',
                'verbose_name_plural': 'Tutor login tarixi',
            },
        ),
    ]
