# Generated by Django 5.1.4 on 2026-04-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_parentloginhistory_tutorloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, default='uz', max_length=10, null=True, verbose_name='Til'),
        ),
    ]
