# Generated by Django 5.1.4 on 2026-05-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0019_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
    ]
