# Generated by Django 5.1.4 on 2026-05-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0020_user_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudentrelation',
            options={'verbose_name': "Ota-ona va farzand bog'lanishi", 'verbose_name_plural': "Ota-ona va farzand bog'lanishlari"},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
        migrations.AlterField(
            model_name='student',
            name='brithday',
            field=models.CharField(max_length=20, verbose_name="Tug'ilgan kun"),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
        migrations.AlterField(
            model_name='student',
            name='type_of_education',
            field=models.CharField(max_length=200, verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='app_user.teacher', verbose_name="O'qituvchilar"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brithday',
            field=models.CharField(max_length=20, verbose_name="Tug'ilgan kun"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_verified_teacher',
            field=models.BooleanField(default=False, verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
    ]
