# Generated by Django 5.1.4 on 2026-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.CharField(max_length=500, blank=True, null=True, verbose_name='url'),
        ),
    ]
