# Generated by Django 5.1.4 on 2026-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_message_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='independent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
