# Generated by Django 5.1.4 on 2026-01-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_message_independent'),
        ('app_user', '0011_teacherloginhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to='app_user.teacher', verbose_name='Chatni yopgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Chat yopilganmi?'),
        ),
        migrations.CreateModel(
            name='ConversationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], verbose_name='Baho')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='app_chat.conversation', verbose_name='Chat')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Chat bahosi',
                'verbose_name_plural': 'Chat baholari',
            },
        ),
    ]
