# Generated by Django 5.1.4 on 2026-01-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_conversation_closed_at_conversation_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Chatni yopgan foydalanuvchi'),
        ),
    ]
