# Generated by Django 5.1.4 on 2026-01-29 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0005_alter_conversation_closed_by'),
        ('app_user', '0012_teacher_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nega o‘tkazildi')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_assignments', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app_chat.conversation')),
                ('from_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='app_user.teacher')),
                ('to_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_to', to='app_user.teacher')),
            ],
        ),
    ]
