# Generated by Django 5.1.4 on 2026-01-29 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0006_conversationassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='close_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopish so‘rovi vaqti'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='close_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_requests', to=settings.AUTH_USER_MODEL, verbose_name='Yopishni so‘ragan'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_close_requested',
            field=models.BooleanField(default=False, verbose_name='Chat yopish so‘ralganmi?'),
        ),
    ]
