# Generated by Django 5.1.4 on 2026-04-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0007_conversation_close_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationrating',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app_chat.conversation', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
    ]
