# Generated by Django 5.1.4 on 2026-05-27 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0008_alter_conversationrating_conversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='close_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Yopish so'rovi vaqti"),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='close_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_requests', to=settings.AUTH_USER_MODEL, verbose_name="Yopishni so'ragan"),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_close_requested',
            field=models.BooleanField(default=False, verbose_name="Chat yopish so'ralganmi?"),
        ),
        migrations.AlterField(
            model_name='conversationassignment',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nega o'tkazildi"),
        ),
        migrations.AlterField(
            model_name='conversationparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi ko'rgan vaqt"),
        ),
        migrations.AlterField(
            model_name='conversationparticipant',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, verbose_name="O'qilmagan xabarlar soni"),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirildimi?"),
        ),
        migrations.AlterField(
            model_name='messagereceipt',
            name='status',
            field=models.CharField(choices=[('delivered', 'Yetkazilgan'), ('read', "O'qilgan")], max_length=10, verbose_name='Holat'),
        ),
    ]
