# Generated by Django 5.1.4 on 2025-09-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_management', '0003_referralandcouponsettings_coupon_student_cashback_percent_and_more'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCouponTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='To‘lov summasi')),
                ('student_cashback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Studentga berilgan keshbek')),
                ('teacher_cashback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Teacherga berilgan keshbek')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Kupon ishlatilgan sana')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_management.coupon_tutor_student', verbose_name='Kupon kodi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_coupons', to='app_user.student', verbose_name='Kuponni ishlatgan student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_transactions', to='app_user.tutor', verbose_name='Kupon egasi (Tutor)')),
            ],
            options={
                'verbose_name': 'Tutor kupon tranzaksiyasi',
                'verbose_name_plural': 'Tutor kupon tranzaksiyalari',
            },
        ),
    ]
