# Generated by Django 5.1.4 on 2025-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorcoupontransaction',
            name='student_cashback_amount',
        ),
        migrations.RemoveField(
            model_name='tutorcoupontransaction',
            name='teacher_cashback_amount',
        ),
        migrations.AddField(
            model_name='tutorcoupontransaction',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="O'qtuvchiga berilgan keshbek"),
        ),
    ]
