# Generated by Django 5.1.4 on 2025-09-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0008_referral_tutor_student'),
        ('app_tutor', '0002_remove_tutorcoupontransaction_student_cashback_amount_and_more'),
        ('app_user', '0002_alter_teacher_options_alter_tutor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='O‘qituvchiga berilgan bonus')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Referal ishlatilgan sana')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_management.referral_tutor_student', verbose_name='Referal kodi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_referrals', to='app_user.student', verbose_name='Referal link orqali kelgan student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to='app_user.tutor', verbose_name='Referal link egasi (Tutor)')),
            ],
            options={
                'verbose_name': 'Tutor referal tranzaksiyasi',
                'verbose_name_plural': 'Tutor referal tranzaksiyalari',
            },
        ),
    ]
