# Generated by Django 5.1.4 on 2025-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0003_tutorreferraltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorreferraltransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='To‘lov summasi'),
            preserve_default=False,
        ),
    ]
