# Generated by Django 5.1.4 on 2025-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0004_tutorreferraltransaction_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorreferraltransaction',
            name='referral',
        ),
    ]
