# Generated by Django 5.1.4 on 2025-10-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0005_remove_tutorreferraltransaction_referral'),
        ('app_user', '0006_alter_parent_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='So‘ralgan summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='So‘ralgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='app_user.tutor', verbose_name='O‘qituvchi')),
            ],
            options={
                'verbose_name': 'O‘qituvchi yechib olish',
                'verbose_name_plural': 'O‘qituvchi yechib olishlar',
            },
        ),
    ]
