# Generated by Django 5.1.4 on 2025-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0006_tutorwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalLimitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Minimal yechib olish summasi')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maksimal yechib olish summasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Yechib olish sozlamalari',
                'verbose_name_plural': 'Yechib olish sozlamalari',
            },
        ),
    ]
