# Generated by Django 5.1.4 on 2026-05-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0007_withdrawallimitsettings'),
        ('app_user', '0021_alter_parentstudentrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorwithdrawal',
            options={'verbose_name': "O'qituvchi yechib olish", 'verbose_name_plural': "O'qituvchi yechib olishlar"},
        ),
        migrations.AlterField(
            model_name='tutorcoupontransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='tutorreferraltransaction',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="O'qituvchiga berilgan bonus"),
        ),
        migrations.AlterField(
            model_name='tutorreferraltransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='tutorwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="So'ralgan summa"),
        ),
        migrations.AlterField(
            model_name='tutorwithdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="So'ralgan vaqt"),
        ),
        migrations.AlterField(
            model_name='tutorwithdrawal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='app_user.tutor', verbose_name="O'qituvchi"),
        ),
    ]
