# Generated by Django 5.1.4 on 2026-09-02 07:31

import django.db.models.deletion
import django_app.app_battle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_teacher', '0010_alter_compositesubquestion_options'),
        ('app_user', '0021_alter_parentstudentrelation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleBotDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin'), ('expert', 'Ekspert')], max_length=10, unique=True)),
                ('accuracy', models.FloatField(help_text="To'g'ri javob berish ehtimoli (0-1)")),
                ('min_answer_seconds', models.FloatField(default=4)),
                ('max_answer_seconds', models.FloatField(default=25)),
            ],
            options={
                'verbose_name': 'Bot qiyinchilik darajasi',
                'verbose_name_plural': 'Bot qiyinchilik darajalari',
            },
        ),
        migrations.CreateModel(
            name='BattleBotIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar_seed', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bot shaxsi',
                'verbose_name_plural': 'Bot shaxslari',
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=False)),
                ('elo_before', models.PositiveIntegerField(default=0)),
                ('elo_after', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_answer_time', models.FloatField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('bot_difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_battle.battlebotdifficulty')),
                ('bot_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_battle.battlebotidentity')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_participations', to='app_user.student')),
            ],
            options={
                'verbose_name': 'Battle ishtirokchisi',
                'verbose_name_plural': 'Battle ishtirokchilari',
            },
        ),
        migrations.CreateModel(
            name='BattleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.PositiveIntegerField(default=800)),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Daraja (0 = Aniqlanmoqda)')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('win_streak', models.PositiveIntegerField(default=0)),
                ('best_elo', models.PositiveIntegerField(default=800)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_rating', to='app_user.student')),
            ],
            options={
                'verbose_name': 'Battle reytingi',
                'verbose_name_plural': 'Battle reytinglari',
                'ordering': ['-elo'],
            },
        ),
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=django_app.app_battle.models.generate_room_code, max_length=8, unique=True)),
                ('subjects_key', models.CharField(db_index=True, default='', help_text='Sorted comma-joined subject ids — matchmaking bucket key.', max_length=200)),
                ('difficulty_level', models.PositiveIntegerField()),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('seconds_per_question', models.PositiveSmallIntegerField(default=60)),
                ('is_random', models.BooleanField(default=True, verbose_name='Tasodifiy raqiblar')),
                ('chat_enabled', models.BooleanField(default=True, verbose_name='Chat yoqilgan')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('active', 'Faol'), ('finished', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='waiting', max_length=10)),
                ('current_question_index', models.PositiveSmallIntegerField(default=0)),
                ('current_question_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_rooms', to='app_user.class')),
                ('subjects', models.ManyToManyField(related_name='battle_rooms', to='app_user.subject')),
                ('winner_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_battle.battleparticipant')),
            ],
            options={
                'verbose_name': 'Battle xonasi',
                'verbose_name_plural': 'Battle xonalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_battle.battleroom'),
        ),
        migrations.CreateModel(
            name='BattleEloLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_before', models.PositiveIntegerField()),
                ('elo_after', models.PositiveIntegerField()),
                ('elo_change', models.IntegerField()),
                ('result', models.CharField(choices=[('win', "G'alaba"), ('loss', 'Mag`lubiyat'), ('draw', 'Durrang')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_elo_logs', to='app_user.student')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elo_logs', to='app_battle.battleroom')),
            ],
            options={
                'verbose_name': 'Battle ELO tarixi',
                'verbose_name_plural': 'Battle ELO tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleRoomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app_teacher.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_battle.battleroom')),
            ],
            options={
                'verbose_name': 'Battle savoli',
                'verbose_name_plural': 'Battle savollari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BattleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answer_time_seconds', models.FloatField(default=0)),
                ('skipped', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_battle.battleparticipant')),
                ('room_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_battle.battleroomquestion')),
            ],
            options={
                'verbose_name': 'Battle javobi',
                'verbose_name_plural': 'Battle javoblari',
            },
        ),
        migrations.AddIndex(
            model_name='battleroom',
            index=models.Index(fields=['status', 'is_random', 'grade', 'subjects_key', 'difficulty_level', 'question_count', 'seconds_per_question'], name='battleroom_matchmaking_idx'),
        ),
        migrations.AddConstraint(
            model_name='battleparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bot_identity__isnull', True), ('student__isnull', False)), models.Q(('bot_identity__isnull', False), ('student__isnull', True)), _connector='OR'), name='battleparticipant_exactly_one_of_student_or_bot'),
        ),
        migrations.AddIndex(
            model_name='battleelolog',
            index=models.Index(fields=['student', 'created_at'], name='battleelolog_student_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='battleroomquestion',
            unique_together={('room', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='battleanswer',
            unique_together={('room_question', 'participant')},
        ),
    ]
