# Generated by Django 5.1.4 on 2026-09-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_battle', '0001_initial'),
        ('app_user', '0021_alter_parentstudentrelation_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='battleroom',
            name='battleroom_matchmaking_idx',
        ),
        migrations.RemoveField(
            model_name='battleroom',
            name='difficulty_level',
        ),
        migrations.AddIndex(
            model_name='battleroom',
            index=models.Index(fields=['status', 'is_random', 'grade', 'subjects_key', 'question_count', 'seconds_per_question'], name='battleroom_matchmaking_idx'),
        ),
    ]
