# Generated by Django 5.1.4 on 2026-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_battle', '0002_remove_battleroom_battleroom_matchmaking_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleelolog',
            name='is_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battlerating',
            name='placement_performance_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='battlerating',
            name='best_elo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlerating',
            name='elo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
