# Generated by Django 5.1.4 on 2025-09-12 05:12

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/BANNER/')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_to_score', models.PositiveIntegerField(default=1, verbose_name='1 tangaga teng ball miqdori')),
                ('coin_to_money', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='1 tangaga teng pul miqdori')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konversiya kursi',
                'verbose_name_plural': 'Konversiya kurslari',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('question_uz', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Javob')),
                ('answer_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Javob')),
                ('answer_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Javob')),
            ],
            options={
                'verbose_name': 'TSS',
                'verbose_name_plural': 'Tez-tez so‘raladigan savollar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Mahsulot rasmi')),
                ('coin', models.PositiveIntegerField(verbose_name='Kerakli tanga')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ReferralAndCouponSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_referral_bonus_points', models.PositiveIntegerField(default=0, verbose_name='O‘qituvchi uchun referal ball')),
                ('student_referral_bonus_points', models.PositiveIntegerField(default=0, verbose_name='O‘quvchi uchun referal ball')),
                ('coupon_discount_percent', models.PositiveIntegerField(default=0, help_text='Kupon kodi orqali beriladigan chegirma foizi', verbose_name='Kupon chegirma foizi')),
                ('coupon_valid_days', models.PositiveIntegerField(default=30, help_text='Kupon kodi amal qilish muddati (kunlarda)', verbose_name='Kupon amal qilish muddati (kun)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Referal va kupon sozlamasi',
                'verbose_name_plural': 'Referal va kupon sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SystemCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kupon kodi')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Chegirma foizi (%)')),
                ('valid_until', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolligi')),
            ],
            options={
                'verbose_name': 'Tizim kuponi',
                'verbose_name_plural': 'Tizim kuponlari',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/logo/', verbose_name='Logo')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Biz Haqimizda')),
                ('about_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Biz Haqimizda')),
                ('about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Biz Haqimizda')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram Linki')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube Linki')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter Linki')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook Linki')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn Linki')),
                ('shartnoma_uz', models.FileField(blank=True, null=True, upload_to='system/docs/uz/', verbose_name="shartnoma (O'zbekcha)")),
                ('shartnoma_ru', models.FileField(blank=True, null=True, upload_to='system/docs/ru/', verbose_name='shartnoma (Ruscha)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="So'nggi yangilanish vaqti")),
            ],
            options={
                'verbose_name': 'Tizim Sozlamasi',
                'verbose_name_plural': 'Tizim Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10, verbose_name='Chegirma foizi')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.student')),
                ('created_by_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.tutor')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='app_management.coupon')),
                ('used_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.student')),
                ('used_by_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.tutor')),
            ],
            options={
                'verbose_name': 'Kupon ishlatilishi',
                'verbose_name_plural': 'Kupon ishlatilishlari',
                'unique_together': {('coupon', 'used_by_student', 'used_by_tutor')},
            },
        ),
    ]
