# Generated by Django 5.1.4 on 2025-09-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_referralandcouponsettings_coupon_student_cashback_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralandcouponsettings',
            name='coupon_student_cashback_percent',
        ),
        migrations.RemoveField(
            model_name='referralandcouponsettings',
            name='coupon_teacher_cashback_percent',
        ),
    ]
