# Generated by Django 5.1.4 on 2025-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0004_remove_referralandcouponsettings_coupon_student_cashback_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralandcouponsettings',
            name='coupon_student_cashback_percent',
            field=models.PositiveIntegerField(default=0, help_text='Kupon ishlatilganda studentga beriladigan keshbek foizi', verbose_name='Student keshbek (%)'),
        ),
        migrations.AddField(
            model_name='referralandcouponsettings',
            name='coupon_teacher_cashback_percent',
            field=models.PositiveIntegerField(default=0, help_text='Kupon ishlatilganda teacherga beriladigan keshbek foizi', verbose_name='Teacher keshbek (%)'),
        ),
    ]
