# Generated by Django 5.1.4 on 2025-09-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_referralandcouponsettings_coupon_student_cashback_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
