# Generated by Django 5.1.4 on 2025-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0006_delete_couponusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_is_active', models.BooleanField(default=False, verbose_name='Fanlar bo‘yicha yechim tugmasi yoqilganmi?')),
                ('recommendation_is_active', models.BooleanField(default=False, verbose_name='Tavsiyalar bo‘yicha yechim tugmasi yoqilganmi?')),
            ],
            options={
                'verbose_name': 'Yechim tugmalari holati',
                'verbose_name_plural': 'Yechim tugmalari holatlari',
            },
        ),
    ]
