# Generated by Django 5.1.4 on 2025-09-26 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0007_solutionstatus'),
        ('app_user', '0002_alter_teacher_options_alter_tutor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_Tutor_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Referal kodi')),
                ('bonus_percent', models.PositiveIntegerField(default=5, verbose_name='Bonus foizi')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.student', verbose_name='Referalni yaratgan student')),
                ('created_by_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.tutor', verbose_name='Referalni yaratgan tutor')),
            ],
            options={
                'verbose_name': 'Referal link',
                'verbose_name_plural': 'Referal linklar',
            },
        ),
    ]
