# Generated by Django 5.1.4 on 2025-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0008_referral_tutor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralandcouponsettings',
            name='referral_valid_days',
            field=models.PositiveIntegerField(default=30, help_text='Referral kodi amal qilish muddati (kunlarda)', verbose_name='Referral amal qilish muddati (kun)'),
        ),
    ]
