# Generated by Django 5.1.4 on 2025-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0009_referralandcouponsettings_referral_valid_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralandcouponsettings',
            name='referral_bonus_coin',
            field=models.PositiveIntegerField(default=0, help_text='Referral kodi orqali beriladigan tanga', verbose_name='Referral  kodi uchun tanga'),
        ),
    ]
