# Generated by Django 5.1.4 on 2025-10-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0010_referralandcouponsettings_referral_bonus_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Mahsulot soni'),
        ),
    ]
