# Generated by Django 5.1.4 on 2025-10-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0011_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='student_referral_bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='O‘quvchi uchun referal foizi'),
        ),
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='teacher_referral_bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='O‘qituvchi uchun referal foizi'),
        ),
    ]
