# Generated by Django 5.1.4 on 2025-10-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0012_alter_referralandcouponsettings_student_referral_bonus_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralandcouponsettings',
            name='referral_bonus_coin',
        ),
    ]
