# Generated by Django 5.1.4 on 2025-11-10 17:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0013_remove_referralandcouponsettings_referral_bonus_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Matn (motivatsion so‘zlar)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Motivatsion matn',
                'verbose_name_plural': 'Motivatsion matnlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
