# Generated by Django 5.1.4 on 2025-11-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0015_category_tag_elon'),
        ('app_user', '0008_alter_student_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_tutor_student',
            name='created_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.teacher'),
        ),
    ]
