# Generated by Django 5.1.4 on 2025-11-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0016_coupon_tutor_student_created_by_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yuklangan fayl',
                'verbose_name_plural': 'Yuklangan fayllar',
            },
        ),
    ]
