# Generated by Django 5.1.4 on 2025-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0017_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralandcouponsettings',
            name='coupon_discount_percent_teacher',
            field=models.PositiveIntegerField(default=0, help_text='Kupon kodi orqali beriladigan chegirma foizi Mentor uchun ', verbose_name='Kupon chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='coupon_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text="Kupon kodi orqali beriladigan chegirma foizi Student va O'qtuvchilar uchun", verbose_name='Kupon chegirma foizi'),
        ),
    ]
