# Generated by Django 5.1.4 on 2025-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0018_referralandcouponsettings_coupon_discount_percent_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='coupon_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text="Kupon kodi orqali beriladigan chegirma foizi Student va O'qtuvchilar uchun", verbose_name="Student va O'qtuvchilar kupon chegirma foizi"),
        ),
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='coupon_discount_percent_teacher',
            field=models.PositiveIntegerField(default=0, help_text='Kupon kodi orqali beriladigan chegirma foizi Mentor uchun ', verbose_name='Mentor kupon chegirma foizi'),
        ),
    ]
