# Generated by Django 5.1.4 on 2025-11-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0019_alter_referralandcouponsettings_coupon_discount_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemCoupon',
        ),
    ]
