# Generated by Django 5.1.4 on 2025-11-30 06:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0020_delete_systemcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn (motivatsion so‘zlar)'),
        ),
        migrations.AddField(
            model_name='motivation',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn (motivatsion so‘zlar)'),
        ),
        migrations.AddField(
            model_name='motivation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='motivation',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
