# Generated by Django 5.1.4 on 2025-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0021_motivation_content_ru_motivation_content_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='news_status',
            field=models.BooleanField(default=False, verbose_name='Yanglik'),
        ),
        migrations.AddField(
            model_name='elon',
            name='notification_status',
            field=models.BooleanField(default=False, verbose_name='Xabarnoma'),
        ),
    ]
