# Generated by Django 5.1.4 on 2025-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0022_elon_news_status_elon_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size_mb', models.PositiveIntegerField(default=5, help_text='Yuklanadigan faylning ruxsat etilgan maksimal hajmi (megabayt)', verbose_name='Maksimal fayl hajmi (MB)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='So‘nggi yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Yuklash hajmi sozlamasi',
                'verbose_name_plural': 'Yuklash hajmi sozlamalari',
            },
        ),
    ]
