# Generated by Django 5.1.4 on 2025-12-27 16:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0023_uploadsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn (boy matn)'),
        ),
        migrations.AddField(
            model_name='elon',
            name='text_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn (boy matn)'),
        ),
        migrations.AddField(
            model_name='elon',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='elon',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
