# Generated by Django 5.1.4 on 2025-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0024_elon_text_ru_elon_text_uz_elon_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_latest_version', models.CharField(max_length=200, verbose_name='Android version')),
                ('android_force_update', models.BooleanField(default=False)),
                ('ios_latest_version', models.CharField(max_length=200, verbose_name='iOS version')),
                ('ios_force_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
