# Generated by Django 5.1.4 on 2026-01-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0025_androidversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
