# Generated by Django 5.1.4 on 2026-01-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0026_faq_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Youtube video link'),
        ),
    ]
