# Generated by Django 5.1.4 on 2026-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0027_alter_faq_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mathematician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Olim FIO')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Olim FIO')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Olim FIO')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Fanlarga qo‘shgan hissasi')),
                ('subtitle_uz', models.CharField(max_length=500, null=True, verbose_name='Fanlarga qo‘shgan hissasi')),
                ('subtitle_ru', models.CharField(max_length=500, null=True, verbose_name='Fanlarga qo‘shgan hissasi')),
                ('life_years', models.CharField(max_length=100, verbose_name='Tug‘ilgan va vafot etgan yillari')),
                ('life_years_uz', models.CharField(max_length=100, null=True, verbose_name='Tug‘ilgan va vafot etgan yillari')),
                ('life_years_ru', models.CharField(max_length=100, null=True, verbose_name='Tug‘ilgan va vafot etgan yillari')),
                ('image', models.ImageField(upload_to='FILES/mathematicians/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name="Batafsil ma'lumot")),
                ('description_uz', models.TextField(null=True, verbose_name="Batafsil ma'lumot")),
                ('description_ru', models.TextField(null=True, verbose_name="Batafsil ma'lumot")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Matematik olim',
                'verbose_name_plural': 'Matematik olimlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
