# Generated by Django 5.1.4 on 2026-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0028_mathematician'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='FILES/Yanglik_Video'),
        ),
    ]
