# Generated by Django 5.1.4 on 2026-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0029_elon_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Youtube video link'),
        ),
    ]
