# Generated by Django 5.1.4 on 2026-01-15 11:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0030_alter_elon_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathematician',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name="Batafsil ma'lumot"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Batafsil ma'lumot"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Batafsil ma'lumot"),
        ),
    ]
