# Generated by Django 5.1.4 on 2026-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0031_alter_mathematician_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCoinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_coin_limit', models.PositiveIntegerField(default=10, help_text="Bir o'quvchi kuniga olishi mumkin bo'lgan maksimal tanga soni", verbose_name='Kunlik tanga chegrasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Kunlik tanga sozlamasi',
                'verbose_name_plural': 'Kunlik tanga sozlamasi',
            },
        ),
    ]
