# Generated by Django 5.1.4 on 2026-05-27 22:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0032_dailycoinsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name': 'TSS', 'verbose_name_plural': "Tez-tez so'raladigan savollar"},
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='life_years',
            field=models.CharField(max_length=100, verbose_name="Tug'ilgan va vafot etgan yillari"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='life_years_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="Tug'ilgan va vafot etgan yillari"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='life_years_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="Tug'ilgan va vafot etgan yillari"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='subtitle',
            field=models.CharField(max_length=500, verbose_name="Fanlarga qo'shgan hissasi"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='subtitle_ru',
            field=models.CharField(max_length=500, null=True, verbose_name="Fanlarga qo'shgan hissasi"),
        ),
        migrations.AlterField(
            model_name='mathematician',
            name='subtitle_uz',
            field=models.CharField(max_length=500, null=True, verbose_name="Fanlarga qo'shgan hissasi"),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name="Matn (motivatsion so'zlar)"),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Matn (motivatsion so'zlar)"),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Matn (motivatsion so'zlar)"),
        ),
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='student_referral_bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name="O'quvchi uchun referal foizi"),
        ),
        migrations.AlterField(
            model_name='referralandcouponsettings',
            name='teacher_referral_bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name="O'qituvchi uchun referal foizi"),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='recommendation_is_active',
            field=models.BooleanField(default=False, verbose_name="Tavsiyalar bo'yicha yechim tugmasi yoqilganmi?"),
        ),
        migrations.AlterField(
            model_name='solutionstatus',
            name='subject_is_active',
            field=models.BooleanField(default=False, verbose_name="Fanlar bo'yicha yechim tugmasi yoqilganmi?"),
        ),
        migrations.AlterField(
            model_name='uploadsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="So'nggi yangilangan vaqti"),
        ),
    ]
