# Generated by Django 5.1.4 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0033_alter_faq_options_alter_mathematician_life_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_count', models.PositiveIntegerField(default=100, verbose_name='Top nechtaga sertifikat beriladi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sertifikat sozlamasi',
                'verbose_name_plural': 'Sertifikat sozlamalari',
            },
        ),
    ]
