# Generated by Django 5.1.4 on 2025-09-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=1000, help_text='Oylik to‘lov summasi (so‘m)')),
            ],
            options={
                'verbose_name': 'Oylik to‘lov',
                'verbose_name_plural': 'Oylik to‘lov',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField(choices=[(1, '1 oylik'), (3, '3 oylik'), (6, '6 oylik'), (12, '12 oylik')], verbose_name='Davomiylik (oy)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma foizi')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oyiga narx')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalar',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_trial_days', models.PositiveIntegerField(default=7, verbose_name='Tekin muddat (kun)')),
            ],
            options={
                'verbose_name': 'Obuna sozlamasi',
                'verbose_name_plural': 'Obuna sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Multicard ID raqami')),
                ('invoice_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoys ID raqami')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='To‘lov tranzaksiyasining  ID raqami')),
                ('billing_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hamkor billing tizimidagi tranzaksiyaning  ID raqami')),
                ('sign', models.CharField(blank=True, max_length=100, null=True, verbose_name='MD5 HASH')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='To‘lov summasi')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Tranzaksiya ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name='To‘lov tizimi')),
                ('receipt_url', models.URLField(blank=True, null=True, verbose_name='To‘lov chek havolasi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_user.student')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Keyingi to‘lov muddati')),
                ('is_paid', models.BooleanField(default=False, verbose_name='To‘langanmi')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='app_user.student')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
    ]
