# Generated by Django 5.1.4 on 2025-09-12 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_referralandcouponsettings_coupon_student_cashback_percent_and_more'),
        ('app_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management.coupon_tutor_student', verbose_name='Ishlatilgan kupon'),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('student', 'Student'), ('system', 'System')], max_length=10, null=True, verbose_name='Kupon turi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma foizi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirmasiz summa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Studentga keshbek'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_months',
            field=models.PositiveIntegerField(default=1, verbose_name='Obuna muddati (oy)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='teacher_cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Teacherga keshbek'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hamkor billing tizimidagi tranzaksiyaning ID raqami'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov tizimi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, null=True, verbose_name="To'lov chek havolasi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov tranzaksiyasining ID raqami"),
        ),
    ]
