# Generated by Django 5.1.4 on 2025-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0003_userpayment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaratilgan sana'),
        ),
    ]
