# Generated by Django 5.1.4 on 2025-09-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_referralandcouponsettings_coupon_student_cashback_percent_and_more'),
        ('app_payments', '0004_alter_userpayment_created_at'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Multicard ID raqami')),
                ('invoice_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoys ID raqami')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov tranzaksiyasining ID raqami")),
                ('billing_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hamkor billing tizimidagi tranzaksiyaning ID raqami')),
                ('sign', models.CharField(blank=True, max_length=100, null=True, verbose_name='MD5 HASH')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi")),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirmasiz summa')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Tranzaksiya ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov tizimi")),
                ('receipt_url', models.URLField(blank=True, null=True, verbose_name="To'lov chek havolasi")),
                ('coupon_type', models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('student', 'Student'), ('system', 'System')], max_length=10, null=True, verbose_name='Kupon turi')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma foizi')),
                ('subscription_months', models.PositiveIntegerField(default=1, verbose_name='Obuna muddati (oy)')),
                ('student_cashback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Studentga keshbek')),
                ('teacher_cashback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Teacherga keshbek')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management.coupon_tutor_student', verbose_name='Ishlatilgan kupon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_user.student')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
