# Generated by Django 5.1.4 on 2025-11-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0005_payment_delete_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPayment',
        ),
    ]
