# Generated by Django 5.1.4 on 2025-11-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0006_delete_monthlypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student_cashback_amount',
        ),
    ]
