# Generated by Django 5.1.4 on 2025-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0007_remove_payment_student_cashback_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student_cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Studentga keshbek'),
        ),
    ]
