# Generated by Django 5.1.4 on 2025-12-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0008_payment_student_cashback_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
