# Generated by Django 5.1.4 on 2025-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0009_subscriptionplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tarif reja nomi:'),
        ),
    ]
