# Generated by Django 5.1.4 on 2025-12-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0011_subscriptioncategory_subscriptionplan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ustunlik nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs ustunligi',
                'verbose_name_plural': 'Kurs ustunliklari',
            },
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tarif reja nomi'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='plans', to='app_payments.subscriptionbenefit', verbose_name='Kurs ustunliklari'),
        ),
    ]
