# Generated by Django 5.1.4 on 2025-12-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0012_subscriptionbenefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (ixtiyoriy)'),
        ),
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (ixtiyoriy)'),
        ),
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ustunlik nomi'),
        ),
        migrations.AddField(
            model_name='subscriptionbenefit',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Ustunlik nomi'),
        ),
        migrations.AddField(
            model_name='subscriptioncategory',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='subscriptioncategory',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
    ]
