# Generated by Django 5.1.4 on 2026-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0013_subscriptionbenefit_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tarif reja nomi'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tarif reja nomi'),
        ),
    ]
