# Generated by Django 5.1.4 on 2026-05-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payments', '0014_subscriptionplan_name_ru_subscriptionplan_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langanmi"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Keyingi to'lov muddati"),
        ),
    ]
