# Generated by Django 5.1.4 on 2026-05-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('draft', 'Qoralama')], default='active', max_length=20, verbose_name='Holat')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='app_book.category', verbose_name='Kategoriya')),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='app_book.tag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
