# Generated by Django 5.1.4 on 2026-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_book_cover_image_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_offline',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Oflayn kitobmi (yetkazib berish mumkin)'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ombordagi soni'),
        ),
    ]
