# Generated by Django 5.1.4 on 2026-05-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0003_book_is_offline_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='book',
            name='for_student',
            field=models.BooleanField(default=False, verbose_name='Student uchun'),
        ),
        migrations.AddField(
            model_name='book',
            name='for_teacher',
            field=models.BooleanField(default=False, verbose_name="O'qituvchi uchun"),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi'),
        ),
    ]
