# Generated by Django 5.1.4 on 2026-05-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0004_book_description_ru_book_description_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('payment_method', models.CharField(choices=[('som', "So'm"), ('coin', 'Tanga'), ('score', 'Ball')], max_length=10, verbose_name="To'lov turi")),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="To'langan jami miqdor")),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app_book.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kitob xaridi',
                'verbose_name_plural': 'Kitob xaridlari',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
