# Generated by Django 5.1.4 on 2026-05-27 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0005_bookpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineBookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('new', 'Yangi buyurtma'), ('seen', "Admin ko'rdi"), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi')], default='new', max_length=20, verbose_name='Yetkazib berish holati')),
                ('delivery_address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_order', to='app_book.bookpurchase', verbose_name='Xarid')),
            ],
            options={
                'verbose_name': 'Oflayn kitob buyurtmasi',
                'verbose_name_plural': 'Oflayn kitob buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
